version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - api_data:/app/data
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend_data:/app/data
    ports:
      - "80:3000"
    networks:
      - app-network
    external_links:
      - api

volumes:
  api_data:
    driver: local
  frontend_data:
    driver: local

networks:
  app-network:
    driver: bridge
